### ISSUE TITLE
add mobile meta classes

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva-searchable-services#19]
currently not looking so hot on mobile! 

![mobile](https://cloud.githubusercontent.com/assets/1943001/6756913/54e88c3c-ceea-11e4-92d9-bcb684a9d362.png)

**Comment by bengolder** [comment]
In general, we should start with mobile, then move to desktop as discussed. If we need more ways to quickly and easily view a mobile version while getting started, I can look into it.

**Comment by mapsam** [comment]
Yup, I agree. There isn't actually anything in the CSS that is for desktop - just forgot the `<meta>` tag statement in the `<head>` so the site scales! Need to add:

``` html
<meta name="viewport" content="width=device-width">
```

**Comment by bengolder** [comment]
Though it clearly has the meta tag, it still looks basically the same to me on mobile:
![image](https://cloud.githubusercontent.com/assets/451510/6956453/24e82c3c-d8a3-11e4-917d-79da3b07dde0.jpg)

Could we reopen as "make mobile friendly"? Or separate smaller pieces? like:
- readable font size on mobile
- tappable buttons on mobile
- format resources to look alright on mobile

**Comment by mapsam** [comment]
It hasn't been merged into the `gh-pages` branch yet, which is why you aren't seeing changes in production. Happy to open up separate issues for the other ones!

FWIW, this hasn't really been designed yet. I'd like to actually talk about the UI with you before pushing it through a design phase where we can talk about what would be useful on mobile. What do you think?
